version: '3.8'

services:
  web:
    build: .
#    command: python manage.py run -h 0.0.0.0
    command: flask run --host=0.0.0.0
    volumes:
      - ./:/base/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev