"""time lables in user model and vocabular model

Revision ID: 71db908d1b53
Revises: 0f1d6acc1bba
Create Date: 2021-12-12 15:43:55.686685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71db908d1b53'
down_revision = '0f1d6acc1bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('vocabular', sa.Column('last_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabular', 'last_check')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
